package com.newbarams.ajaja.module.user.application.service;

import com.newbarams.ajaja.module.user.application.model.AccessToken;

public interface AuthorizeService {
	/**
	 * @param authorizationCode Key for authorize which generated by Oauth
	 * @return Access token
	 */
	AccessToken authorize(String authorizationCode, String redirectUri);
}
