spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(gsAzfECEKoAU2CMbA1Y9CecUhbFMhFI/7GC6fGqhT2D+0/b4guGo/wunh0pDf+u/3XUQ3rkBzr67pMi73y8dINeSPdlFCEmdv8mUcstFWTIpi15fQZTXfg==)
    username: ENC(pj2OQDc7CO49Fd/+rLWsjg==)
    password: ENC(APbEe0qcK2StKZlNHQ3XQxKzaMigf+1D)

  data:
    redis:
      host: ENC(ViAmf82rY15XKPYHcLP0QRYfJYl+TGZv)

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(tGwdWhKp3JANKDooNLD7c4uxrljB6JUuL0RGqUTIwf8INRmmQEAUbMMZY4XpcinE)
    username: ENC(sU5cFR/NcS3lcWR+BE7tJw==)
    password: ENC(E0BPQSOtdRe3yrRS/F2AZ9iCkzZfXAT8)
