###
# @name mock 로그인
POST {{path}}/mock/login?code=authorizationCode

> {% client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken); %}

###
# @name 실제 로그인
POST {{path}}/login
Content-Type: application/json

{
  "authorizationCode": "WXx4mr0d7vn-7k60QnQnK_ZWUdMNCjOGf-APGZnAp5twPUT9eVvOX_ypwPUKKcleAAABjABcxpLokopMIboAuA",
  "redirectUri": "http://localhost:3000/oauth"
}

###
# @name 토큰 재발급
POST {{path}}/reissue
Content-Type: application/json

{
  "accessToken": "{{accessToken}}",
  "refreshToken": "{{refreshToken}}"
}

###
# @name 닉네임 새로고침
POST {{path}}/users/refresh
Authorization: Bearer {{accessToken}}

###
# @name 이메일 인증요청
POST {{path}}/users/send-verification
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": ""
}

###
# @name 인증번호 검증
POST {{path}}/users/verify
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "certification": ""
}

###
# @name 로그아웃
POST {{path}}/users/logout
Authorization: Bearer {{accessToken}}
