ALTER TABLE users
    DROP COLUMN id,
    ADD COLUMN user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    CHANGE COLUMN status is_deleted BOOLEAN NOT NULL;

ALTER TABLE tags
    DROP COLUMN id,
    ADD COLUMN tag_id BIGINT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE reminds
    DROP COLUMN id,
    ADD COLUMN remind_id BIGINT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE plans
    DROP COLUMN id,
    ADD COLUMN plan_id BIGINT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE feedbacks
    DROP COLUMN id,
    ADD COLUMN feedback_id BIGINT PRIMARY KEY AUTO_INCREMENT;
