ALTER TABLE plans
    MODIFY COLUMN title VARCHAR(20) NOT NULL,
    MODIFY COLUMN description VARCHAR(250) NOT NULL;
ALTER TABLE remind_messages
    MODIFY COLUMN content VARCHAR(250) NOT NULL;
ALTER TABLE reminds
    MODIFY COLUMN content VARCHAR(250) NOT NULL;
