name: check convention, test w/ jacoco

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

env:
  GRADLE_VERSION: 8.3
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle w/ caching
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          cache-read-only: true # will be update

      - name: Check Code Convention
        run: gradle check

      - name: Check Tests w/ Test Coverage
        run: gradle testWithCoverage

      - name: Add Coverage on Pull Request
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Test Coverage Report

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Clean Build w/o TEST, CHECK
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: clean build -x test -x check
