name: convention check w/ jacoco

on:
  pull_request:
    branches:
      - prod
      - dev

permissions:
  checks: write
  pull-requests: write

env:
  GRADLE_VERSION: 8.3
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle w/ caching
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Check Code Convention
        run: ./gradlew -x test check

      - name: Check Tests w/ Test Coverage
        run: ./gradlew testWithJacoco

      - name: Add Coverage on Pull Request
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          title: Test Coverage Report

