name: auto assign

on:
  pull_request:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          ready-comment: 'Ready for review :ok:'
